// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7b1ZBJYVm7S5UDbA7bneJ9H4qw_ZVxo8',
    appId: '1:1059598722133:web:edf48bb545901fdbc860dc',
    messagingSenderId: '1059598722133',
    projectId: 'clinic-app-c8f4c',
    authDomain: 'clinic-app-c8f4c.firebaseapp.com',
    storageBucket: 'clinic-app-c8f4c.appspot.com',
    measurementId: 'G-2T9ZCPFV1D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjZ78h0gxs6otuQSQh-O7EWxny7akV2LE',
    appId: '1:1059598722133:android:be540668e101143ec860dc',
    messagingSenderId: '1059598722133',
    projectId: 'clinic-app-c8f4c',
    storageBucket: 'clinic-app-c8f4c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtmzRnyX86CUrXd5Kk0K5kQddjT-DKA00',
    appId: '1:1059598722133:ios:faae18afc3f1eac3c860dc',
    messagingSenderId: '1059598722133',
    projectId: 'clinic-app-c8f4c',
    storageBucket: 'clinic-app-c8f4c.appspot.com',
    iosBundleId: 'com.kamisofts.clinicsApp',
  );
}
